linters:
  enable:
    - errcheck
    - staticcheck
    - unused

issues:
  exclude-rules:
    # Exclude errcheck for test files - test cleanup code often ignores errors intentionally
    - path: _test\.go
      linters:
        - errcheck
    # Exclude errcheck for example files
    - path: examples/
      linters:
        - errcheck
