version: "2"

linters:
  enable:
    - errcheck
    - staticcheck
    - unused
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - errcheck
      - path: 'examples/'
        linters:
          - errcheck
