version: 2

project_name: recall

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: recall
    main: ./cmd/recall
    binary: recall
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: hyperengineering
    name: recall
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"

nfpms:
  - id: packages
    package_name: recall
    vendor: Hyper Engineering
    homepage: "https://github.com/hyperengineering/recall"
    maintainer: Lauri Jutila
    description: "CLI for managing experiential lore from AI agent workflows"
    license: MIT
    formats:
      - deb
    bindir: /usr/bin
    section: utils
    priority: optional
    contents:
      - src: LICENSE.md
        dst: /usr/share/doc/recall/copyright
      - src: README.md
        dst: /usr/share/doc/recall/README.md

publishers:
  - name: fury.io
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_PUSH_TOKEN }}@push.fury.io/neuralmux/

brews:
  - name: recall
    repository:
      owner: hyperengineering
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/hyperengineering/recall"
    description: "CLI for managing experiential lore from AI agent workflows"
    license: "MIT"
    install: |
      bin.install "recall"
    test: |
      system "#{bin}/recall", "version"

dockers:
  - image_templates:
      - "ghcr.io/hyperengineering/recall:{{ .Tag }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title=recall"
      - "--label=org.opencontainers.image.description=CLI for managing experiential lore"
      - "--label=org.opencontainers.image.source=https://github.com/hyperengineering/recall"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - image_templates:
      - "ghcr.io/hyperengineering/recall:{{ .Tag }}-arm64"
    dockerfile: Dockerfile
    use: buildx
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title=recall"
      - "--label=org.opencontainers.image.description=CLI for managing experiential lore"
      - "--label=org.opencontainers.image.source=https://github.com/hyperengineering/recall"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"

docker_manifests:
  - name_template: "ghcr.io/hyperengineering/recall:{{ .Tag }}"
    image_templates:
      - "ghcr.io/hyperengineering/recall:{{ .Tag }}-amd64"
      - "ghcr.io/hyperengineering/recall:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/hyperengineering/recall:v{{ .Major }}"
    image_templates:
      - "ghcr.io/hyperengineering/recall:{{ .Tag }}-amd64"
      - "ghcr.io/hyperengineering/recall:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/hyperengineering/recall:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/hyperengineering/recall:{{ .Tag }}-amd64"
      - "ghcr.io/hyperengineering/recall:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/hyperengineering/recall:latest"
    image_templates:
      - "ghcr.io/hyperengineering/recall:{{ .Tag }}-amd64"
      - "ghcr.io/hyperengineering/recall:{{ .Tag }}-arm64"
